# Sample Dockerfile

# Indicates that the windowsservercore image will be used as the base image.
FROM microsoft/nanoserver

# Metadata indicating an image maintainer.
MAINTAINER drmiru@hotmail.com

# Copy ASP.NET Core App to image
COPY ExpertsApp /apps/


   